### PR TITLE
Typography

### PR DESCRIPTION
**Pull request by YOGINIMAHIMA1**
Use more consistent font sizes across the page. The text in the "Waste Management" link seems small compared to the rest of the navigation. Aim for uniformity in text size to improve readability.

### CODE REVIEW

**Comment by GarimaSingh0109** [comment]
@YOGINIMAHIMA1 add ss of you work(not code)

**Comment by YOGINIMAHIMA1** [comment]
image

**Review by GarimaSingh0109 — APPROVED** [review]

**Comment by YOGINIMAHIMA1** [comment]
@GarimaSingh0109  I have changed the text size of "waste management" to improve readability.

**Comment by YOGINIMAHIMA1** [comment]
@GarimaSingh0109 add level1 label to it so that i got points

**Comment by YOGINIMAHIMA1** [comment]
@GarimaSingh0109 add level1 label to it

**Comment by YOGINIMAHIMA1** [comment]
@GarimaSingh0109  add label to it

**Comment by YOGINIMAHIMA1** [comment]
@GarimaSingh0109  add label to it pls

**Pull request merged**
