### PR TITLE
rate us

### LINKED ISSUE #7: Creating rate us feature
I would like to add rate us feature in this website.
Kindly close this req if u find my work appropriate

### PR DESCRIPTION
**Pull request by Codewithmeowmeow**
Rate us feature is added using emojis.
and appropriate message will be shown on the screen

fixes #7 
i have resolve the conflict.

### CODE REVIEW

**Comment by GarimaSingh0109** [comment]
@Codewithmeowmeow add ss of your work and resolve contflict

**Comment by Codewithmeowmeow** [comment]
> @Codewithmeowmeow add ss of your work and resolve contflict

Done. Can you please review and merge this pr now

**Comment by GarimaSingh0109** [comment]
@Codewithmeowmeow good job add issue no and resolve conflict

**Comment by Codewithmeowmeow** [comment]
> @Codewithmeowmeow good job add issue no and resolve conflict

resolved conflict.

**Review by GarimaSingh0109 — APPROVED** [review]

**Pull request merged**
