### PR TITLE
Adding FAQs Section to the website

### PR DESCRIPTION
**Pull request by aditiverma-21**
This section provides essential guidance to users on various aspects of waste management and engages them with interactive, easy-to-access answers!

### CODE REVIEW

**Comment by GarimaSingh0109** [comment]
@aditiverma-21 add ss of your work

**Comment by aditiverma-21** [comment]
Yes sure

**Comment by aditiverma-21** [comment]
image
image
image

**Comment by aditiverma-21** [comment]
https://github.com/user-attachments/assets/b54d9148-f32e-4dc2-b791-df4170130e11

**Comment by aditiverma-21** [comment]
@GarimaSingh0109 please check the ss and video

**Comment by GarimaSingh0109** [comment]
@aditiverma-21 good job

**Review by GarimaSingh0109 — APPROVED** [review]

**Comment by GarimaSingh0109** [comment]
@aditiverma-21 add your issue no

**Comment by aditiverma-21** [comment]
yes sure in the title? or in comment?

**Comment by aditiverma-21** [comment]
@GarimaSingh0109 I added issue no to title

**Pull request merged**
