### PR TITLE
Implemented seamless realtime waste monitoring feature

### PR DESCRIPTION
**Pull request by Nkovaturient**
## Issues Identification

Closes: #166 

### Summary
Added RTM feature for users to input their waste data and track their waste disposals.

### Details
Here is illustrated preview video of the feature:-

1. Users can input their waste data and visualize it through charts
2. Waste Segregation step is the crucial first and foremost step that must be taken by each individual from their waste source level.

https://github.com/user-attachments/assets/d2ff77a3-aada-4a7c-8dc6-4157f5947ea6

## Types of Changes

_Please check the boxes that apply_

- [ ] Bugfix (non-breaking change that fixes an issue)
- [✅ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [✅ ] My code follows the style guidelines of this project
- [ ✅ ] I have performed a self-review of my own code
- [✅  ] I have commented my code, particularly in hard-to-understand areas
- [✅  ] I have made corresponding changes to the documentation
- [✅  ] My changes generate no new warnings
- [✅  ] My changes do not break the current system and pass all existing test cases
- [✅  ] I have added tests that prove my fix is effective or that my feature works
- [✅  ] New and existing unit tests pass locally with my changes
- [ ✅ ] Any dependent changes have been merged and published in downstream modules

## Summary by CodeRabbit

- **New Features**
	- Overhauled eco-tips section with new entries and updated content.
	- Introduced a real-time monitoring dashboard for waste management.
	- Added a feature slider for showcasing app functionalities.
	- Implemented a "Scroll to Top" button for improved navigation.
	- Added a "Waste Categories" section for better organization.

- **Bug Fixes**
	- Enhanced newsletter form validation.

- **Style**
	- Updated styles for responsiveness and dark mode, including new utility classes.
	- Improved layout and organization of CSS for better clarity.

### CODE REVIEW

**Comment by khushi-joshi-05** [comment]
@Nkovaturient solve conflicts

**Comment by Nkovaturient** [comment]
> @Nkovaturient solve conflicts

hey @khushi-joshi-05 @GarimaSingh0109 , I have fixed the conflicts. Kindly look into it and guide me.

**Comment by Nkovaturient** [comment]
@khushi-joshi-05 @GarimaSingh0109 
Conflict resolved as per updates.

**Comment by Nkovaturient** [comment]
@khushi-joshi-05 @GarimaSingh0109 Hey there?!
Any updates or other issues that I must resolve?

**Comment by khushi-joshi-05** [comment]
Still showing conflicts

**Comment by Nkovaturient** [comment]
Hey @GarimaSingh0109 , @khushi-joshi-05 
the conflicts are recurring due to continuous updates, diff and merged PRs at the same place  in the code lines.
However, I have meticulously resolved it keeping the features, styling, and js functionality working.

One thing I would like to say--the main styles.css file is becoming bulky and inefficient due to continuous css integrations and changes, this may impact the overall code and website performance + loading. Kindly look into it and suggest guidance to contributors to only make necessary changes, while ensuring code efficiency and modularity.

**Review by GarimaSingh0109 — APPROVED** [review]

**Pull request merged**
