### PR TITLE
Update signUp.html

### PR DESCRIPTION
**Pull request by Aryam2121**
Attractive Background: A gradient background adds visual interest and warmth to the page.

Password Visibility Toggle: Users can now click an icon to toggle password visibility, improving usability.

Client-Side Validation: Simple JavaScript checks to ensure passwords match before form submission.

Error Message Display: An error message appears if the passwords do not match, providing instant feedback to users.

Improved Button Styles: The button has a modern design and hover effects for better interactivity.

Responsive Design: The form remains user-friendly on various devices.

Semantic HTML: Proper use of HTML structure to ensure accessibility and SEO.solve issue #9

## Issues Identification

Closes: #9 

### Summary
Provide a brief description of what this pull request does and why it is needed.

### Details
Include any detailed information about the changes in this pull request.

## Types of Changes

_Please check the boxes that apply_

- [x] Bugfix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update (Documentation content changed)
- [x] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes do not break the current system and pass all existing test cases
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Screenshots

If applicable, please attach screenshots of the changes made to the user interface.

## Additional Information

Please provide any other information that is relevant to this pull request.

### CODE REVIEW

**Comment by Aryam2121** [comment]
Merge this code in your repository

**Comment by khushi-joshi-05** [comment]
@Aryam2121 solve conflicts.

**Comment by Aryam2121** [comment]
what conflicts my code is right

**Comment by khushi-joshi-05** [comment]
Screenshot_20241018_160855_Chrome
In the sign-up.html file

**Comment by GarimaSingh0109** [comment]
@Aryam2121 pr close due to issue not assigned

**Comment by Aryam2121** [comment]
What is this.I solve your issue so you assign me and merge if someone who you assign don't work on that issue

**Pull request closed without merging**
