### PR TITLE
Added a new Log in Page and within this page created a link to new     si…

### PR DESCRIPTION
**Pull request by ParulPrashar**
…gn in page. Designed a new Sign in page fully. 
The following are the images of 2 newly created pages.

Screenshot (15)
Screenshot (16)
Screenshot (17)
Screenshot (18)
Screenshot (19)

### CODE REVIEW

**Comment by GarimaSingh0109** [comment]
@ParulPrashar resolve conflict

**Comment by ParulPrashar** [comment]
@GarimaSingh0109 mam kindly add the labels please, else I will miss this out. Hacktoberfest and gssoc and level please

**Comment by ParulPrashar** [comment]
@GarimaSingh0109 Please add the labels

**Comment by ParulPrashar** [comment]
@GarimaSingh0109 mam please add labels my contribution is not going to have worth then

**Pull request merged**
