### PR TITLE
I have made some changes to both the HTML file and added an image to the assets folder and I also made changes in the CSS file.

### PR DESCRIPTION
**Pull request by anchalchaturvedi08**
Merge back into the main

### CODE REVIEW

**Comment by anchalchaturvedi08** [comment]
> @anchalchaturvedi08 add ss of your work and resolve conflicts

Mam,
I need a review to merge this pull request, but the "Request Reviewers" button is not clickable. Could you please help me by assigning a reviewer and checking the permissions?
Thankyou.

**Comment by anchalchaturvedi08** [comment]
IMG_20241004_164348
I have added the new image and hover effect on the navbar lists

**Comment by anchalchaturvedi08** [comment]
IMG_20241004_164425
In this ecotips HTML file, I have just edited the sentence.

**Comment by anchalchaturvedi08** [comment]
IMG_20241004_164439
In the footer section, I have just added the hover effect in the social media section

**Comment by GarimaSingh0109** [comment]
@anchalchaturvedi08 Resolve conflict

**Comment by anchalchaturvedi08** [comment]
@GarimaSingh0109 

I have resolved all conflicts in the pull request, retaining the changes from my b1 branch. Please proceed with merging the pull request and add the labels.

**Review by GarimaSingh0109 — APPROVED** [review]

**Pull request merged**
