### PR TITLE
The Signup Page Enhancement

### PR DESCRIPTION
**Pull request by Lekkhasri**
## Issues Identification  

Closes: #172 

## Description
The sign up page looks very blind where the header contains all the links that not take to the respective pages. But now the issue is solved and the continue with google option is also added, which enhance the user friendly platform to user.
Also for security the password has certain conditions like 8 words uppercase, lowercase and special characters.
### Summary
The sign up page and login page looks very attractive and the user feels it very friendly

### Details
1. The header section contains many content which are removed .
2.  The footer section has also been added successfully.
## Types of Changes

_Please check the boxes that apply_

- [ ] Bugfix (non-breaking change that fixes an issue)
- [  ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [  ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [  ] My code follows the style guidelines of this project
- [  ] I have performed a self-review of my own code
- [  ] I have commented my code, particularly in hard-to-understand areas
- [  ] I have made corresponding changes to the documentation
- [  ] My changes generate no new warnings
- [  ] My changes do not break the current system and pass all existing test cases
- [  ] I have added tests that prove my fix is effective or that my feature works
-  [  ] New and existing unit tests pass locally with my changes
- [  ] Any dependent changes have been merged and published in downstream modules

## Screenshots
before:
image
after:
image
image
image
image
image

If applicable, please attach screenshots of the changes made to the user interface.

## Additional Information

If you need further any changes in the code i am ready to do it . @GarimaSingh0109

### CODE REVIEW

**Review by GarimaSingh0109 — APPROVED** [review]

**Comment by GarimaSingh0109** [comment]
@Lekkhasri resolve conflicts

**Comment by Lekkhasri** [comment]
@GarimaSingh0109 there is no conflicts now mam

**Comment by Lekkhasri** [comment]
@khushi-joshi-05 can you assign the labels please

**Comment by Lekkhasri** [comment]
@GarimaSingh0109 and @khushi-joshi-05 can you assign the labels please

**Pull request merged**
