### PR TITLE
enhanced CSS of Home page and made the scrolling smoother , also styles ecotips page

### PR DESCRIPTION
**Pull request by daichianoop**
## Issues Identification

Closes: #(issue number)

### Summary
I have added some animations to the navbar , creating hover effects and translate effects. 
I have also added styles to ecotips pages designing the page for better readability and view

### Details
There is a change in the Ecotips.html and index.html . In index.html , i have added styles in navbar and in eco tips page o have made a css file named ecotips.css and edited the html page for better readability , i have also corrected some spelling mistakes.

## Types of Changes

_Please check the boxes that apply_

- [ ] Bugfix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe):

## Checklist

_Please check the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes do not break the current system and pass all existing test cases
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots

If applicable, please attach screenshots of the changes made to the user interface.

## Additional Information

Please provide any other information that is relevant to this pull request.

### CODE REVIEW

**Comment by daichianoop** [comment]
Thank you

**Comment by khushi-joshi-05** [comment]
Screenshot_20241018_161106_Chrome
@daichianoop Have u just copied and pasted the desc, read it once and provide proper details.

**Comment by daichianoop** [comment]
ok ill correct it

**Comment by GarimaSingh0109** [comment]
@daichianoop pr closed due to issue not assigned

**Pull request closed without merging**
